/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.StringTokenizer;
import javax.swing.JOptionPane;
import lab2.pkg1_willian_garcia_william_morelo.Nodo;
import static vista.Principal.end;
import static vista.Principal.root;

/**
 *
 * @author Estudiante
 */
public class Registar extends javax.swing.JFrame {

    /**
     * Creates new form Registar
     */
    public Registar() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cta = new javax.swing.JTextField();
        fecha = new javax.swing.JTextField();
        monto = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Numero cta");

        jLabel2.setText("Fecha");

        jLabel3.setText("Monto");

        jButton1.setText("Registrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Volver");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Formato de fecha DD/MM/AAAA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(monto, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(fecha, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cta, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(monto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            StringTokenizer st1 = new StringTokenizer(fecha.getText(),"/");
            if(monto.getText().equals("") || cta.getText().equals("") || fecha.getText().equals(""))
            JOptionPane.showMessageDialog(null, "nos es posible crear la cuenta con campos vacios");
            else if(Float.parseFloat(monto.getText())<100000) JOptionPane.showMessageDialog(null, "nos es posible crear la cuenta monto minimo 100000");
            else if(st1.countTokens()!=3 ){
            JOptionPane.showMessageDialog(null, "Error formato invalido");
            }else{
                try{
                int d1,m1,a1,d2,m2,a2;
                    d1=Integer.parseInt(st1.nextToken());
                    m1=Integer.parseInt(st1.nextToken());
                    a1=Integer.parseInt(st1.nextToken());
                    if(a1<0){
                        JOptionPane.showMessageDialog(null, "Error años no pueden ser negativos");
                    }else if(m1<=0 || m1>12){
                        JOptionPane.showMessageDialog(null, "Error meses fuera de los limites");
                    }else if(d1<=0 || //dias negativos
                            ((m1==1 || m1==3 || m1==5 || m1==7 || m1==8 || m1==10 || m1==12) && d1>31)||//+31 dias
                            (m1==2 && d1>28) ||//+28dias
                            ((m1==4 || m1==6 || m1==9 || m1==11) && d1>28)) {
                        JOptionPane.showMessageDialog(null, "Error dias fuera de los limites");
                    }else crear();
                }catch(NumberFormatException e){
                    JOptionPane.showMessageDialog(null, "Error fecha solo puede ser numerico");
                }   
            }
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Error monto solo puede ser numerico");
        }
        fecha.setText("");
        monto.setText("");
        cta.setText("");
       mostrar(new SimpleDateFormat("dd/MM/yyyy"));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        Principal v1=new Principal();
        v1.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed
    private void crear(){
        try{
            SimpleDateFormat formatoDelTexto = new SimpleDateFormat("dd/MM/yyyy");
            Date dt =null;
            try{
            dt = formatoDelTexto.parse(fecha.getText());
            Nodo temp=new Nodo(dt,Long.parseLong(cta.getText()),Float.parseFloat(monto.getText()),true);
                if(root!=null){
                  Nodo aux=root;
                  moverse(aux,temp);
                }else{
                 end=root=temp;
                 JOptionPane.showMessageDialog(null, "Cuenta Creada");
                }
            }catch (ParseException ex) {
                
            }
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "numero de cuenta debe ser numerico");
        }
        
}
    public void mostrar(SimpleDateFormat ft){
        Nodo aux=root;
       while(aux!=null){
           System.out.println(aux.getNro()+" "+ ft.format(aux.getFecha())+" "+aux.getMonto());
           aux=aux.getRl();
       }
       if(root!=null && end!=null)System.out.println("root "+root.getNro()+" end "+end.getNro());
    } 
    private void moverse(Nodo temp,Nodo add){
        if(temp.getRl()==null ){
            if(temp.getNro()==add.getNro()){
            JOptionPane.showMessageDialog(null, "Esta nro de cuenta ya existe");
            }else if(add.getNro()<temp.getNro()){
                add.setRl(temp);
                JOptionPane.showMessageDialog(null, "Cuenta Creada");
                root=add;
            }else{
                temp.setRl(add);
                JOptionPane.showMessageDialog(null, "Cuenta Creada");
                end=temp=add;
            }
        }else if(temp.getNro()==add.getNro()){
            JOptionPane.showMessageDialog(null, "Esta nro de cuenta ya existe");
        }else if(add.getNro()<temp.getNro()){
                add.setRl(temp);
                JOptionPane.showMessageDialog(null, "Cuenta Creada");
                root=add;
        }else{
            moverse(temp.getRl(),add);
        }        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cta;
    private javax.swing.JTextField fecha;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField monto;
    // End of variables declaration//GEN-END:variables
}
